# Generated by Django 5.2.9 on 2026-01-05 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Ensayos', 'Ensayos'), ('Show / Toque', 'Show / Toque'), ('Grabación', 'Grabación'), ('Escucha', 'Escucha'), ('Reunión', 'Reunión')], default='Ensayos', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
