# Generated by Django 5.2.9 on 2026-01-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_art', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Idea', 'Idea'), ('Demo', 'Demo'), ('Polishing', 'Polishing'), ('Ready', 'Ready')], default='Idea', max_length=20)),
                ('type', models.CharField(choices=[('Original', 'Original'), ('Cover', 'Cover')], default='Original', max_length=20)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('original_artist', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='repertoire.album')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('spotify', 'Spotify'), ('drive', 'Drive'), ('youtube', 'YouTube'), ('other', 'Other')], default='other', max_length=20)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='repertoire.song')),
            ],
        ),
    ]
